version: '3'

services:

  nginx:
    build:
        context: .
        dockerfile: Dockerfile.nginx
    image: psicothepato/nginx
    container_name: nginx
    networks:
      - trident-net
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
        - MYSQL_DATABASe=nodedb
        - MYSQL_ROOT_PASSWORD=root
    networks:
      - trident-net

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: psicothepato/node
    container_name: node
    tty: true
    volumes:
      - ./app:/usr/src/app
    networks:
      - trident-net
    ports:
      - "3000:3000"

networks:
  trident-net:
    driver: bridge